# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Branberg
email: hello@branberg.com
description: "We craft digital experiences - A studio committed to great ideas."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://branberg.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: branberg
dribbble_username: mikberg
home_title: "We craft digital experiences."
home_subtitle: "A studio committed to great ideas."
work_title: "From concept to creation and beyond, we work with incredible people to make great digital products."
work_site_link: "Website"
asset_path: "./assets"
contact_email: "&#104;&#101;&#108;&#108;&#111;&#64;&#98;&#114;&#97;&#110;&#98;&#101;&#114;&#103;&#46;&#99;&#111;&#109;"
physical_location: "Minneapolis, MN"

# Build settings
markdown: kramdown
